server:
  port: 13001

logging:
  level:
    root: info
  file:
    name: ./log/muthub-core.log

spring:
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true
  application:
    name: muthub-core
